import { DatasetRow, ResourceItem, User } from '../src/types.js';

export const INITIAL_USERS: User[] = [
  {
    id: 'EMP001',
    username: 'admin',
    name: 'Sarah Jenkins (SecAdmin)',
    role: 'Security Officer',
    accountType: 'Admin',
    department: 'Cybersecurity Operations',
  },
  {
    id: 'EMP002',
    username: 'dev_alex',
    name: 'Alex Rivera',
    role: 'Software Engineer',
    accountType: 'Standard',
    department: 'Engineering',
  },
  {
    id: 'EMP003',
    username: 'sys_marcus',
    name: 'Marcus Vance',
    role: 'System Admin',
    accountType: 'Privileged',
    department: 'IT Infrastructure',
  },
  {
    id: 'EMP004',
    username: 'devops_priya',
    name: 'Priya Sharma',
    role: 'DevOps Engineer',
    accountType: 'Privileged',
    department: 'Cloud Ops',
  },
  {
    id: 'EMP005',
    username: 'hr_elena',
    name: 'Elena Rostova',
    role: 'HR Specialist',
    accountType: 'Standard',
    department: 'Human Resources',
  },
  {
    id: 'EMP006',
    username: 'fin_david',
    name: 'David Kim',
    role: 'Financial Analyst',
    accountType: 'Standard',
    department: 'Finance & Compliance',
  },
];

export const AVAILABLE_RESOURCES: ResourceItem[] = [
  {
    id: 'RES-01',
    name: 'Production-DB Cluster',
    category: 'Database',
    baselineRisk: 'Critical',
    requiredPrivilege: 'Admin-Root',
    description: 'Primary customer SQL relational database storing core transactional data.',
  },
  {
    id: 'RES-02',
    name: 'Financial-Records Vault',
    category: 'Finance',
    baselineRisk: 'High',
    requiredPrivilege: 'Read-Only',
    description: 'Secure vault for payroll, quarterly statements, and revenue metrics.',
  },
  {
    id: 'RES-03',
    name: 'Core Code Repository',
    category: 'Source Code',
    baselineRisk: 'Medium',
    requiredPrivilege: 'Write',
    description: 'Main Git repository for microservices, backend APIs, and frontend code.',
  },
  {
    id: 'RES-04',
    name: 'HR-Employee Portal',
    category: 'Human Resources',
    baselineRisk: 'Low',
    requiredPrivilege: 'Read-Only',
    description: 'Internal directory for employee contact info, leave records, and reviews.',
  },
  {
    id: 'RES-05',
    name: 'AWS Cloud Admin Console',
    category: 'Cloud Infrastructure',
    baselineRisk: 'Critical',
    requiredPrivilege: 'Admin-Root',
    description: 'IAM, VPC, Kubernetes clusters, and cloud gateway configuration.',
  },
  {
    id: 'RES-06',
    name: 'K8s Production Deployer',
    category: 'Deployment',
    baselineRisk: 'High',
    requiredPrivilege: 'Execute',
    description: 'CI/CD runner for launching container releases into production environments.',
  },
];

// Cleaned & Feature-Engineered Dataset (20 required columns)
export const SEED_DATASET: DatasetRow[] = [
  // Normal Approved Requests
  {
    User_ID: 'EMP002',
    Role: 'Software Engineer',
    Account_Type: 'Standard',
    Login_Time: '09:15',
    Login_Location: 'HQ-NewYork',
    Device_Type: 'Corporate-Laptop',
    Authentication_Method: 'Password+MFA',
    Failed_Login_Attempts: 0,
    Resource_Accessed: 'Core Code Repository',
    Requested_Privilege: 'Write',
    Requested_Duration: 60,
    Temporary_Access: 'Yes',
    Access_Frequency: 'Daily',
    Session_Duration: 45,
    New_Device: 0,
    New_Location: 0,
    Risk_Score: 12.5,
    Access_Decision: 'GRANT',
    Attack_Type: 'Normal',
    Anomaly: 0,
  },
  {
    User_ID: 'EMP003',
    Role: 'System Admin',
    Account_Type: 'Privileged',
    Login_Time: '10:30',
    Login_Location: 'HQ-NewYork',
    Device_Type: 'Corporate-Laptop',
    Authentication_Method: 'Hardware-Key',
    Failed_Login_Attempts: 0,
    Resource_Accessed: 'Production-DB Cluster',
    Requested_Privilege: 'Admin-Root',
    Requested_Duration: 30,
    Temporary_Access: 'Yes',
    Access_Frequency: 'Daily',
    Session_Duration: 25,
    New_Device: 0,
    New_Location: 0,
    Risk_Score: 18.0,
    Access_Decision: 'GRANT',
    Attack_Type: 'Normal',
    Anomaly: 0,
  },
  {
    User_ID: 'EMP004',
    Role: 'DevOps Engineer',
    Account_Type: 'Privileged',
    Login_Time: '14:00',
    Login_Location: 'Remote-Boston',
    Device_Type: 'Corporate-Laptop',
    Authentication_Method: 'Password+MFA',
    Failed_Login_Attempts: 0,
    Resource_Accessed: 'K8s Production Deployer',
    Requested_Privilege: 'Execute',
    Requested_Duration: 45,
    Temporary_Access: 'Yes',
    Access_Frequency: 'Daily',
    Session_Duration: 40,
    New_Device: 0,
    New_Location: 0,
    Risk_Score: 22.4,
    Access_Decision: 'GRANT',
    Attack_Type: 'Normal',
    Anomaly: 0,
  },
  {
    User_ID: 'EMP005',
    Role: 'HR Specialist',
    Account_Type: 'Standard',
    Login_Time: '11:20',
    Login_Location: 'HQ-NewYork',
    Device_Type: 'Corporate-Laptop',
    Authentication_Method: 'Password+MFA',
    Failed_Login_Attempts: 0,
    Resource_Accessed: 'HR-Employee Portal',
    Requested_Privilege: 'Read-Only',
    Requested_Duration: 120,
    Temporary_Access: 'Yes',
    Access_Frequency: 'Daily',
    Session_Duration: 90,
    New_Device: 0,
    New_Location: 0,
    Risk_Score: 8.0,
    Access_Decision: 'GRANT',
    Attack_Type: 'Normal',
    Anomaly: 0,
  },
  {
    User_ID: 'EMP006',
    Role: 'Financial Analyst',
    Account_Type: 'Standard',
    Login_Time: '13:45',
    Login_Location: 'Remote-Boston',
    Device_Type: 'Corporate-Laptop',
    Authentication_Method: 'Hardware-Key',
    Failed_Login_Attempts: 0,
    Resource_Accessed: 'Financial-Records Vault',
    Requested_Privilege: 'Read-Only',
    Requested_Duration: 60,
    Temporary_Access: 'Yes',
    Access_Frequency: 'Daily',
    Session_Duration: 50,
    New_Device: 0,
    New_Location: 0,
    Risk_Score: 15.2,
    Access_Decision: 'GRANT',
    Attack_Type: 'Normal',
    Anomaly: 0,
  },

  // Anomalous & Threat Scenarios (Privilege Escalation, Credential Stuffing, Impossible Travel, etc.)
  {
    User_ID: 'EMP002',
    Role: 'Software Engineer',
    Account_Type: 'Standard',
    Login_Time: '02:40',
    Login_Location: 'Unknown-IP',
    Device_Type: 'Unknown-Linux',
    Authentication_Method: 'Password-Only',
    Failed_Login_Attempts: 4,
    Resource_Accessed: 'Production-DB Cluster',
    Requested_Privilege: 'Admin-Root',
    Requested_Duration: 480,
    Temporary_Access: 'No',
    Access_Frequency: 'First-Time',
    Session_Duration: 120,
    New_Device: 1,
    New_Location: 1,
    Risk_Score: 89.5,
    Access_Decision: 'DENY',
    Attack_Type: 'Privilege Escalation',
    Anomaly: 1,
  },
  {
    User_ID: 'EMP005',
    Role: 'HR Specialist',
    Account_Type: 'Standard',
    Login_Time: '03:15',
    Login_Location: 'Offshore-India',
    Device_Type: 'BYOD-MacBook',
    Authentication_Method: 'Password-Only',
    Failed_Login_Attempts: 5,
    Resource_Accessed: 'AWS Cloud Admin Console',
    Requested_Privilege: 'Admin-Root',
    Requested_Duration: 240,
    Temporary_Access: 'No',
    Access_Frequency: 'Rare',
    Session_Duration: 180,
    New_Device: 1,
    New_Location: 1,
    Risk_Score: 94.2,
    Access_Decision: 'DENY',
    Attack_Type: 'Credential Stuffing',
    Anomaly: 1,
  },
  {
    User_ID: 'EMP003',
    Role: 'System Admin',
    Account_Type: 'Privileged',
    Login_Time: '10:35',
    Login_Location: 'Offshore-India',
    Device_Type: 'Unknown-Linux',
    Authentication_Method: 'Password-Only',
    Failed_Login_Attempts: 2,
    Resource_Accessed: 'Financial-Records Vault',
    Requested_Privilege: 'Read-Only',
    Requested_Duration: 180,
    Temporary_Access: 'Yes',
    Access_Frequency: 'First-Time',
    Session_Duration: 60,
    New_Device: 1,
    New_Location: 1,
    Risk_Score: 78.6,
    Access_Decision: 'DENY',
    Attack_Type: 'Impossible Travel',
    Anomaly: 1,
  },
  {
    User_ID: 'EMP004',
    Role: 'DevOps Engineer',
    Account_Type: 'Privileged',
    Login_Time: '01:10',
    Login_Location: 'Unknown-IP',
    Device_Type: 'Corporate-Laptop',
    Authentication_Method: 'Password-Only',
    Failed_Login_Attempts: 3,
    Resource_Accessed: 'Production-DB Cluster',
    Requested_Privilege: 'Admin-Root',
    Requested_Duration: 360,
    Temporary_Access: 'No',
    Access_Frequency: 'Rare',
    Session_Duration: 200,
    New_Device: 0,
    New_Location: 1,
    Risk_Score: 82.1,
    Access_Decision: 'DENY',
    Attack_Type: 'Off-Hours Mass Access',
    Anomaly: 1,
  },
  {
    User_ID: 'EMP006',
    Role: 'Financial Analyst',
    Account_Type: 'Standard',
    Login_Time: '16:20',
    Login_Location: 'HQ-NewYork',
    Device_Type: 'Corporate-Laptop',
    Authentication_Method: 'Password+MFA',
    Failed_Login_Attempts: 0,
    Resource_Accessed: 'AWS Cloud Admin Console',
    Requested_Privilege: 'Admin-Root',
    Requested_Duration: 120,
    Temporary_Access: 'Yes',
    Access_Frequency: 'First-Time',
    Session_Duration: 30,
    New_Device: 0,
    New_Location: 0,
    Risk_Score: 68.4,
    Access_Decision: 'DENY',
    Attack_Type: 'Unauthorized Resource Access',
    Anomaly: 1,
  },
  {
    User_ID: 'EMP002',
    Role: 'Software Engineer',
    Account_Type: 'Standard',
    Login_Time: '11:00',
    Login_Location: 'HQ-NewYork',
    Device_Type: 'Corporate-Laptop',
    Authentication_Method: 'Password+MFA',
    Failed_Login_Attempts: 0,
    Resource_Accessed: 'Core Code Repository',
    Requested_Privilege: 'Write',
    Requested_Duration: 30,
    Temporary_Access: 'Yes',
    Access_Frequency: 'Daily',
    Session_Duration: 30,
    New_Device: 0,
    New_Location: 0,
    Risk_Score: 11.0,
    Access_Decision: 'GRANT',
    Attack_Type: 'Normal',
    Anomaly: 0,
  },
  {
    User_ID: 'EMP001',
    Role: 'Security Officer',
    Account_Type: 'Admin',
    Login_Time: '08:45',
    Login_Location: 'HQ-NewYork',
    Device_Type: 'Corporate-Laptop',
    Authentication_Method: 'Hardware-Key',
    Failed_Login_Attempts: 0,
    Resource_Accessed: 'AWS Cloud Admin Console',
    Requested_Privilege: 'Admin-Root',
    Requested_Duration: 60,
    Temporary_Access: 'Yes',
    Access_Frequency: 'Daily',
    Session_Duration: 40,
    New_Device: 0,
    New_Location: 0,
    Risk_Score: 14.8,
    Access_Decision: 'GRANT',
    Attack_Type: 'Normal',
    Anomaly: 0,
  },
  {
    User_ID: 'EMP003',
    Role: 'System Admin',
    Account_Type: 'Privileged',
    Login_Time: '15:10',
    Login_Location: 'HQ-NewYork',
    Device_Type: 'Corporate-Laptop',
    Authentication_Method: 'Hardware-Key',
    Failed_Login_Attempts: 0,
    Resource_Accessed: 'K8s Production Deployer',
    Requested_Privilege: 'Execute',
    Requested_Duration: 30,
    Temporary_Access: 'Yes',
    Access_Frequency: 'Daily',
    Session_Duration: 20,
    New_Device: 0,
    New_Location: 0,
    Risk_Score: 19.5,
    Access_Decision: 'GRANT',
    Attack_Type: 'Normal',
    Anomaly: 0,
  },
  {
    User_ID: 'EMP005',
    Role: 'HR Specialist',
    Account_Type: 'Standard',
    Login_Time: '04:00',
    Login_Location: 'Unknown-IP',
    Device_Type: 'Unknown-Linux',
    Authentication_Method: 'Password-Only',
    Failed_Login_Attempts: 6,
    Resource_Accessed: 'Production-DB Cluster',
    Requested_Privilege: 'Admin-Root',
    Requested_Duration: 300,
    Temporary_Access: 'No',
    Access_Frequency: 'Rare',
    Session_Duration: 150,
    New_Device: 1,
    New_Location: 1,
    Risk_Score: 96.8,
    Access_Decision: 'DENY',
    Attack_Type: 'Privilege Escalation',
    Anomaly: 1,
  },
  {
    User_ID: 'EMP004',
    Role: 'DevOps Engineer',
    Account_Type: 'Privileged',
    Login_Time: '10:00',
    Login_Location: 'Remote-Boston',
    Device_Type: 'Corporate-Laptop',
    Authentication_Method: 'Password+MFA',
    Failed_Login_Attempts: 0,
    Resource_Accessed: 'Core Code Repository',
    Requested_Privilege: 'Write',
    Requested_Duration: 60,
    Temporary_Access: 'Yes',
    Access_Frequency: 'Daily',
    Session_Duration: 55,
    New_Device: 0,
    New_Location: 0,
    Risk_Score: 13.1,
    Access_Decision: 'GRANT',
    Attack_Type: 'Normal',
    Anomaly: 0,
  },
];
